### ISSUE TITLE
Upstream has changed makefile?

### ISSUE THREAD

**Issue by gwern** [alfiedotwtf/bitcoin-on-debian#2]
I tried using the script today to install bitcoind to run a full node on a new Hetzner dedicated server using their debian-87-jessie-64-minimal OS image (uname: Linux danbooru 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux). I ran into two issues: configuration failed due to headers for the DB being missing (`apt-get install libdb-dev` didn't seem to fix it so I had to add `./configure --disable-wallet`), and running the top level make file didn't work, yielding an error like

    make[1]: Entering directory '/root/bitcoin-on-debian/bitcoin'
    make[1]: *** No rule to make target 'install'.  Stop.
    make[1]: Leaving directory '/root/bitcoin-on-debian/bitcoin'
    Makefile:57: recipe for target 'install' failed
    make: *** [install] Error 2
    make: Leaving directory '/root/bitcoin-on-debian'
    $ cd bitcoin-on-debian/bitcoin
    $ make install
    make: *** No rule to make target 'install'.  Stop.

What did work was manually cding into the Bitcoin repo, and running `autogen.sh`/`configure --disable-wallet`/`make -j8`/`make install`.

The new `docs/unix-build.md` seems to imply that you can't simply call `make install` in it? But have to `make` it first? Something to look into.

**Comment by alfiedotwtf** [comment]
Hey Gwern!

I just tried building this with a virgin Jessie under Vagrant, but it failed. Investigating, just like https://github.com/alfiedotwtf/bitcoin-on-debian/issues/1, it turned out to be the OOM Killer. Grepping /var/log/messages confirmed it:

  cc1plus invoked oom-killer

I upped swap on the VM to 4G but it still failed to hide from the OOM Killer.

Not having a Jessie host, I tried on my Sid box (that has 10Gb swap). Compiled and installed perfectly.

Can you please add swap to the box (at least 10Gb) and let me know if it compiles successfully? If so, I'll update the documentation to say you need lots of memory. The easy way to do this would be:

  https://github.com/alfiedotwtf/swapfile-simple

Before doing a `make install` here, edit the Makefile and up BLOCKCOUNT to at least 5000.

Let me know if that works for you.

Alfie

**Comment by gwern** [comment]
This was a 16GB RAM server and it errored out so instantly without doing any compilation I could see that OOM seems unlikely.

**Comment by alfiedotwtf** [comment]
Hey again,

Sorry for the late reply, I've been sick the past couple of days.

Looking at the error message you had, it does look like the `install` target doesn't exist. This would only happen if there was an issue with creating the Makefile. The autogen and configure like you say, should have created this properly.

I tried again on a virgin Jessie, upped the RAM, added swap, and it built fine. Please see:

    https://gist.github.com/alfiedotwtf/1da5ae3e104e4d85f961c9cadb364b53

Please do me a favour:

    cd <bitcoin-on-debian-directory>
    script
    make clean
    make install

If this still fails to build:

    date
    grep oom /var/log/messages
    exit

Then post the created typescript file to a gist so I can have a look at it and try and help you further.

**Comment by gwern** [comment]
[typescript.txt](https://github.com/alfiedotwtf/bitcoin-on-debian/files/850884/typescript.txt)

**Comment by alfiedotwtf** [comment]
Apart from OOM issues, I've never seen this issue before (and I've used this on Hashicorp images and multiple upstream Debian ISOs). It does look like something on your box is messing with BDB. 

Could you try using a different Debian image, or even upstream's ISOs.

**Comment by gwern** [comment]
That's not possible. It would be way too much work to reinstall and risk wiping out all the data on it now which would take ages to reupload.

**Comment by alfiedotwtf** [comment]
Could you try spinning up another box with that same image, and try again? That way, you'll know if it's the image that's having issues, or something that you've installed.

**Comment by gwern** [comment]
I could but I don't care enough about this issue to go through setting up an entire new VPS or dedicated server. If you can't replicate it, oh well.
