### ISSUE TITLE
Update to bitcoin-0.14.1 enquiry

### ISSUE THREAD

**Issue by ChrisPNoodles** [alfiedotwtf/bitcoin-on-debian#3]
Hello Alfie

Hope you don’t mind me asking a newbie question here – more a question than an “issue” as such.

Decided a few months ago to run a bitcoin full node, and expose myself to Linux into the bargain - so I acquired a low-power min-PC https://www.amazon.co.uk/Braswell-Celeron-Quad-Fanless-Barebone/dp/B01GBHCHDI/ref=cm_cr_arp_d_product_top?ie=UTF8 and, after checking out various Linux flavours, set it up with Debian Jessie. Your Github project was an absolute godsend, worked a treat, installing Bitcoin Core 0.13.2. The unit has been running fine since then, as an always-on “appliance” used for the bitcoin node, Samba file-share, and a couple of other things. 

Anyway decided today I’d better get it up to date – did the OS and now I’m trying to figure out (as an inexperienced Linux user) how to update the installation. Trawling around the ‘net, I see quite a few mentions of Linux bitcoin updates saying “just overwrite the binaries” and I’m thinking that will possibly work – I downloaded and unzipped bitcoin-0.14.1-x86_64-linux-gnu.tar.gz, and I can see the /bin directory.

However if I run a search against the file system looking for “bitcoind”, I can see there are copies of the shared library in /usr/local/bin and also /home/chris/bitcoin-on-debian/bitcoin/src    

So I’m feeling a bit nervous about overwriting stuff, wonder if you could provide me with some reassurance / insight / advice on how to proceed.

Thanks for your great project, and (hopefully) advice 

Chris

**Comment by alfiedotwtf** [comment]
Sorry, I must have missed the notification :(

Are you still having this issue?

I'm probably not the right person to be asking because I don't want you to lose you wallet! Maybe better confirm what to do at bitcointalk.org

But what I would do is stop the service, then backup the wallet.dat file, along with all the other files onto an external storage device so that if anything fails, you can always copy back.

Then, install as per my docs.

Then, copy back the wallet.dat file, and the blocks/ directory.

Hopefully that should get things going.

**Comment by ChrisPNoodles** [comment]
Thanks Alfie - still running the downlevel version at the moment (and wallet.dat is empty). 

I'll give it a go sometime in the next few days
